// --------------------
// FILE: fly.toml (optional if generated via fly launch)
// --------------------
# fly.toml app configuration
app = "trustgap-scraper-flyio"
primary_region = "iad"

[build]
  builder = "heroku/buildpacks:20"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
